<a href="https://colab.research.google.com/github/SamyakMundre/Netflix-Clone/blob/main/IPL2025AnalysisData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df = pd.read_csv("/content/IPL2025Batters.csv")

In [2]:
df.head()

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37

In [3]:
df.tail()

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
151,Khaleel Ahmed,CSK,1,14,2,2,1*,-,2,50.00,0,0,0,0
152,Mohit Sharma,DC,1,8,2,1,1*,1.00,3,33.33,0,0,0,0
153,Donovan Ferreira,DC,1,1,1,0,1,1.00,3,33.33,0,0,0,0
154,Digvesh Singh,LSG,1,13,2,1,1,1.00,3,33.33,0,0,0,0
155,Manoj Bhandage,RCB,1,1,1,0,1,1.00,4,25.00,0,0,0,0

In [4]:
df.shape

(156, 14)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Player Name  156 non-null    object
 1   Team         156 non-null    object
 2   Runs         156 non-null    int64
 3   Matches      156 non-null    int64
 4   Inn          156 non-null    int64
 5   No           156 non-null    int64
 6   HS           156 non-null    object
 7   AVG          156 non-null    object
 8   BF           156 non-null    int64
 9   SR           156 non-null    float64
 10  100s         156 non-null    int64
 11  50s          156 non-null    int64
 12  4s           156 non-null    int64
 13  6s           156 non-null    int64
dtypes: float64(1), int64(9), object(4)
memory usage: 17.2+ KB

In [6]:
df.describe()

,Runs,Matches,Inn,No,BF,SR,100s,50s,4s,6s
count,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000
mean,161.320513,9.865385,7.153846,1.634615,105.673077,134.394103,0.057692,0.916667,14.391026,8.294872
std,180.352772,4.757455,4.810142,1.658163,112.191838,57.237148,0.233912,1.590124,17.778774,9.515500
min,1.000000,1.000000,1.000000,0.000000,1.000000,25.000000,0.000000,0.000000,0.000000,0.000000
25%,10.750000,6.000000,2.750000,0.000000,12.000000,100.000000,0.000000,0.000000,1.000000,0.000000
50%,93.500000,11.000000,6.000000,1.000000,63.500000,140.005000,0.000000,0.000000,7.000000,4.000000
75%,254.250000,14.000000,12.000000,3.000000,164.750000,162.707500,0.000000,1.000000,23.000000,14.000000
max,759.000000,17.000000,17.000000,7.000000,486.000000,400.000000,1.000000,8.000000,88.000000,40.000000

In [7]:
df.columns

Index(['Player Name', 'Team', 'Runs', 'Matches', 'Inn', 'No', 'HS', 'AVG',
       'BF', 'SR', '100s', '50s', '4s', '6s'],
      dtype='object')

In [8]:
df.dtypes

Player Name     object
Team            object
Runs             int64
Matches          int64
Inn              int64
No               int64
HS              object
AVG             object
BF               int64
SR             float64
100s             int64
50s              int64
4s               int64
6s               int64
dtype: object

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Player Name  156 non-null    object
 1   Team         156 non-null    object
 2   Runs         156 non-null    int64
 3   Matches      156 non-null    int64
 4   Inn          156 non-null    int64
 5   No           156 non-null    int64
 6   HS           156 non-null    object
 7   AVG          156 non-null    object
 8   BF           156 non-null    int64
 9   SR           156 non-null    float64
 10  100s         156 non-null    int64
 11  50s          156 non-null    int64
 12  4s           156 non-null    int64
 13  6s           156 non-null    int64
dtypes: float64(1), int64(9), object(4)
memory usage: 17.2+ KB

In [10]:
df.isnull().sum()

Player Name    0
Team           0
Runs           0
Matches        0
Inn            0
No             0
HS             0
AVG            0
BF             0
SR             0
100s           0
50s            0
4s             0
6s             0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.describe()

,Runs,Matches,Inn,No,BF,SR,100s,50s,4s,6s
count,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000
mean,161.320513,9.865385,7.153846,1.634615,105.673077,134.394103,0.057692,0.916667,14.391026,8.294872
std,180.352772,4.757455,4.810142,1.658163,112.191838,57.237148,0.233912,1.590124,17.778774,9.515500
min,1.000000,1.000000,1.000000,0.000000,1.000000,25.000000,0.000000,0.000000,0.000000,0.000000
25%,10.750000,6.000000,2.750000,0.000000,12.000000,100.000000,0.000000,0.000000,1.000000,0.000000
50%,93.500000,11.000000,6.000000,1.000000,63.500000,140.005000,0.000000,0.000000,7.000000,4.000000
75%,254.250000,14.000000,12.000000,3.000000,164.750000,162.707500,0.000000,1.000000,23.000000,14.000000
max,759.000000,17.000000,17.000000,7.000000,486.000000,400.000000,1.000000,8.000000,88.000000,40.000000

In [13]:
df["Team"].unique()

array(['GT', 'MI', 'RCB', 'LSG', 'PBKS', 'RR', 'DC', 'SRH', 'KKR', 'CSK'],
      dtype=object)

In [14]:
df["Team"].nunique()

10

In [15]:
top_runs = df.sort_values(by="Runs",ascending = False)
top_runs.head(10)

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37
5,Shreyas Iyer,PBKS,604,17,17,5,97*,50.33,345,175.07,0,6,43,39
6,Yashasvi Jaiswal,RR,559,14,14,1,75,43.00,350,159.71,0,6,60,28
7,Prabhsimran Singh,PBKS,549,17,17,0,91,32.29,342,160.52,0,4,56,30
8,K L Rahul,DC,539,13,13,3,112*,53.90,360,149.72,1,3,52,21
9,Jos Buttler,GT,538,14,13,4,97*,59.78,330,163.03,0,5,52,24

In [16]:
df.sort_values(by="SR", ascending=False).head(10)

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
137,Lockie Ferguson,PBKS,4,4,1,1,4*,-,1,400.00,0,0,1,0
124,Kwena Maphaka,RR,8,2,1,1,8*,-,2,400.00,0,0,2,0
129,Akash Deep,LSG,6,6,2,1,6*,6.00,2,300.00,0,0,0,1
84,Romario Shepherd,RCB,70,8,3,1,53*,35.00,24,291.66,0,1,5,7
109,Jamie Overton,CSK,15,3,2,2,11*,-,7,214.28,0,0,1,1
85,Urvil Patel,CSK,68,3,3,0,37,22.67,32,212.50,0,0,5,6
39,Vaibhav Suryavanshi,RR,252,7,7,0,101,36.00,122,206.55,1,1,18,24
125,Raj Angad Bawa,MI,8,3,1,1,8*,-,4,200.00,0,0,0,0
105,Kusal Mendis,GT,20,1,1,0,20,20.00,10,200.00,0,0,1,2
10,Nicholas Pooran,LSG,524,14,14,2,87*,43.67,267,196.25,0,5,45,40

In [17]:
df.sort_values(by="6s", ascending=False).head(10)

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
10,Nicholas Pooran,LSG,524,14,14,2,87*,43.67,267,196.25,0,5,45,40
5,Shreyas Iyer,PBKS,604,17,17,5,97*,50.33,345,175.07,0,6,43,39
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37
7,Prabhsimran Singh,PBKS,549,17,17,0,91,32.29,342,160.52,0,4,56,30
6,Yashasvi Jaiswal,RR,559,14,14,1,75,43.00,350,159.71,0,6,60,28
14,Abhishek Sharma,SRH,439,14,13,0,141,33.77,227,193.39,1,2,46,28
17,Riyan Parag,RR,393,14,14,2,95,32.75,236,166.52,0,1,27,27
11,Heinrich Klaasen,SRH,487,13,13,2,105*,44.27,282,172.69,1,1,42,25
12,Priyansh Arya,PBKS,475,17,17,0,103,27.94,265,179.24,1,2,55,25

In [18]:
df.sort_values(by="4s", ascending=False).head(10)

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
6,Yashasvi Jaiswal,RR,559,14,14,1,75,43.00,350,159.71,0,6,60,28
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37
7,Prabhsimran Singh,PBKS,549,17,17,0,91,32.29,342,160.52,0,4,56,30
12,Priyansh Arya,PBKS,475,17,17,0,103,27.94,265,179.24,1,2,55,25
9,Jos Buttler,GT,538,14,13,4,97*,59.78,330,163.03,0,5,52,24
8,K L Rahul,DC,539,13,13,3,112*,53.90,360,149.72,1,3,52,21

In [19]:
df.sort_values(by="100s", ascending = False)

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
11,Heinrich Klaasen,SRH,487,13,13,2,105*,44.27,282,172.69,1,1,42,25
8,K L Rahul,DC,539,13,13,3,112*,53.90,360,149.72,1,3,52,21
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37
14,Abhishek Sharma,SRH,439,14,13,0,141,33.77,227,193.39,1,2,46,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,Khaleel Ahmed,CSK,1,14,2,2,1*,-,2,50.00,0,0,0,0
152,Mohit Sharma,DC,1,8,2,1,1*,1.00,3,33.33,0,0,0,0
153,Donovan Ferreira,DC,1,1,1,0,1,1.00,3,33.33,0,0,0,0
154,Digvesh Singh,LSG,1,13,2,1,1,1.00,3,33.33,0,0,0,0
155,Manoj Bhandage,RCB,1,1,1,0,1,1.00,4,25.00,0,0,0,0

In [20]:
df.sort_values(by = "50s", ascending= False).head(10)

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37
6,Yashasvi Jaiswal,RR,559,14,14,1,75,43.00,350,159.71,0,6,60,28
5,Shreyas Iyer,PBKS,604,17,17,5,97*,50.33,345,175.07,0,6,43,39
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
9,Jos Buttler,GT,538,14,13,4,97*,59.78,330,163.03,0,5,52,24
10,Nicholas Pooran,LSG,524,14,14,2,87*,43.67,267,196.25,0,5,45,40
13,Aiden Markram,LSG,445,13,13,0,66,34.23,299,148.82,0,5,38,22

In [21]:
team_runs = df.groupby("Team")["Runs"].sum()
print(team_runs)

Team
CSK     2315
DC      2386
GT      2766
KKR     1886
LSG     2598
MI      2802
PBKS    3000
RCB     2539
RR      2496
SRH     2378
Name: Runs, dtype: int64

In [22]:
team_runs.sort_values(ascending=False)

Team
PBKS    3000
MI      2802
GT      2766
LSG     2598
RCB     2539
RR      2496
DC      2386
SRH     2378
CSK     2315
KKR     1886
Name: Runs, dtype: int64

In [23]:
df.groupby("Team")["SR"].mean().sort_values(ascending=False)

Team
PBKS    144.912667
GT      142.952857
RCB     141.392857
LSG     140.846667
MI      137.221250
RR      137.220000
CSK     130.346842
SRH     129.773571
KKR     123.555333
DC      119.012941
Name: SR, dtype: float64

In [24]:
df.groupby("Team")["6s"].sum().sort_values(ascending=False)

Team
PBKS    173
LSG     152
RR      146
MI      142
RCB     125
GT      124
SRH     120
DC      109
CSK     102
KKR     101
Name: 6s, dtype: int64

In [25]:
df.groupby("Team")["4s"].sum().sort_values(ascending=False)

Team
MI      259
GT      256
PBKS    255
RCB     238
SRH     219
DC      219
LSG     218
RR      209
CSK     199
KKR     173
Name: 4s, dtype: int64

In [27]:
df["Runs"].sum()

np.int64(25166)

In [28]:
df["Runs"].mean()

np.float64(161.32051282051282)

In [29]:
df["Runs"].max()

759

In [31]:
df["Runs"].min()

1

In [32]:
df["SR"].mean()

np.float64(134.39410256410258)

In [34]:
df["AVG"]= pd.to_numeric(df["AVG"], errors = "coerce")

In [35]:
df["AVG"].isnull().sum()

np.int64(15)

In [37]:
df["AVG"].mean()

np.float64(23.08723404255319)

In [39]:
df.corr(numeric_only=True)

,Runs,Matches,Inn,No,AVG,BF,SR,100s,50s,4s,6s
Runs,1.000000,0.562155,0.879385,0.218436,0.811337,0.990562,0.349464,0.420423,0.874217,0.972971,0.930254
Matches,0.562155,1.000000,0.744069,0.520411,0.340449,0.566610,0.055588,0.180949,0.413836,0.510460,0.555838
Inn,0.879385,0.744069,1.000000,0.442270,0.667311,0.885002,0.312416,0.301697,0.662982,0.820847,0.855724
No,0.218436,0.520411,0.442270,1.000000,0.367618,0.220717,0.119068,-0.061737,0.071571,0.120210,0.237079
AVG,0.811337,0.340449,0.667311,0.367618,1.000000,0.791954,0.650401,0.290090,0.674650,0.761884,0.762257
BF,0.990562,0.566610,0.885002,0.220717,0.791954,1.000000,0.302441,0.395299,0.869373,0.961525,0.891057
SR,0.349464,0.055588,0.312416,0.119068,0.650401,0.302441,1.000000,0.143433,0.245441,0.332809,0.404466
100s,0.420423,0.180949,0.301697,-0.061737,0.290090,0.395299,0.143433,1.000000,0.255845,0.439783,0.398108
50s,0.874217,0.413836,0.662982,0.071571,0.674650,0.869373,0.245441,0.255845,1.000000,0.874521,0.779367
4s,0.972971,0.510460,0.820847,0.120210,0.761884,0.961525,0.332809,0.439783,0.874521,1.000000,0.861225
6s,0.930254,0.555838,0.855724,0.237079,0.762257,0.891057,0.404466,0.398108,0.779367,0.861225,1.000000

In [40]:
df[["Runs","AVG","SR","4s","6s"]].corr()

          Runs       AVG        SR        4s        6s
Runs  1.000000  0.811337  0.349464  0.972971  0.930254
AVG   0.811337  1.000000  0.650401  0.761884  0.762257
SR    0.349464  0.650401  1.000000  0.332809  0.404466
4s    0.972971  0.761884  0.332809  1.000000  0.861225
6s    0.930254  0.762257  0.404466  0.861225  1.000000

In [41]:
df["Boundary Runs"] = (df["4s"]*4) + (df["6s"]*6)

In [42]:
df.head()

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s,Boundary Runs
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21,478
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38,504
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19,378
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24,392
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37,446

In [43]:
df[df["Runs"] > 500]

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s,Boundary Runs
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21,478
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38,504
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19,378
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24,392
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37,446
5,Shreyas Iyer,PBKS,604,17,17,5,97*,50.33,345,175.07,0,6,43,39,406
6,Yashasvi Jaiswal,RR,559,14,14,1,75,43.00,350,159.71,0,6,60,28,408
7,Prabhsimran Singh,PBKS,549,17,17,0,91,32.29,342,160.52,0,4,56,30,404
8,K L Rahul,DC,539,13,13,3,112*,53.90,360,149.72,1,3,52,21,334
9,Jos Buttler,GT,538,14,13,4,97*,59.78,330,163.03,0,5,52,24,352
10,Nicholas Pooran,LSG,524,14,14,2,87*,43.67,267,196.25,0,5,45,40,420

In [44]:
df[df["SR"] > 150]

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s,Boundary Runs
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21,478
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38,504
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24,392
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37,446
5,Shreyas Iyer,PBKS,604,17,17,5,97*,50.33,345,175.07,0,6,43,39,406
6,Yashasvi Jaiswal,RR,559,14,14,1,75,43.00,350,159.71,0,6,60,28,408
7,Prabhsimran Singh,PBKS,549,17,17,0,91,32.29,342,160.52,0,4,56,30,404
9,Jos Buttler,GT,538,14,13,4,97*,59.78,330,163.03,0,5,52,24,352
10,Nicholas Pooran,LSG,524,14,14,2,87*,43.67,267,196.25,0,5,45,40,420
11,Heinrich Klaasen,SRH,487,13,13,2,105*,44.27,282,172.69,1,1,42,25,318
12,Priyansh Arya,PBKS,475,17,17,0,103,27.94,265,179.24,1,2,55,25,370
14,Abhishek Sharma,SRH,439,14,13,0,141,33.77,227,193.39,1,2,46,28,352
16,Phil Salt,RCB,403,13,13,1,65,33.58,229,175.98,0,4,48,22,324
17,Riyan Parag,RR,393,14,14,2,95,32.75,236,166.52,0,1,27,27,270
19,Ryan Rickelton,MI,388,14,14,1,62*,29.85,257,150.97,0,3,47,17,290
20,Travis Head,SRH,374,13,12,0,76,31.17,230,162.60,0,3,50,15,290
23,Ishan Kishan,SRH,354,14,13,3,106*,35.40,232,152.58,1,1,33,15,222
24,Shashank Singh,PBKS,350,17,14,7,61*,50.00,228,153.50,0,3,23,18,200
26,Dhruv Jurel,RR,333,14,13,4,70,37.00,213,156.33,0,2,22,22,220
31,Tristan Stubbs,DC,300,14,13,7,41*,50.00,199,150.75,0,0,25,11,166
33,Sherfane Rutherford,GT,291,13,11,2,46,32.33,185,157.29,0,0,22,18,196
35,Josh Inglis,PBKS,278,11,11,2,73,30.89,171,162.57,0,1,26,16,200
37,Axar Patel,DC,263,12,11,1,43,26.30,167,157.48,0,0,23,15,182
38,Jitesh Sharma,RCB,261,15,11,4,85*,37.29,148,176.35,0,1,24,17,198
39,Vaibhav Suryavanshi,RR,252,7,7,0,101,36.00,122,206.55,1,1,18,24,216
40,Naman Dhir,MI,252,16,12,4,46,31.50,138,182.60,0,0,24,13,174
41,Devdutt Padikkal,RCB,247,10,10,1,61,27.44,164,150.60,0,2,21,14,168
42,Sunil Narine,KKR,246,12,12,1,44,22.36,144,170.83,0,0,25,19,214
43,Ayush Mhatre,CSK,240,7,7,0,94,34.29,127,188.97,0,1,31,11,190
45,Aniket Verma,SRH,236,14,12,3,74,26.22,142,166.19,0,1,12,20,168
47,Dewald Brevis,CSK,225,6,6,0,57,37.50,125,180.00,0,2,13,17,154
48,Hardik Pandya,MI,224,15,12,3,48*,24.89,137,163.50,0,0,18,12,144
49,Nitish Rana,RR,217,11,11,1,81,21.70,134,161.94,0,2,27,9,162
50,Rinku Singh,KKR,206,13,11,4,38*,29.43,134,153.73,0,0,20,10,140
51,Ashutosh Sharma,DC,204,13,9,2,66*,29.14,127,160.62,0,1,14,13,134
53,Karun Nair,DC,198,8,8,0,89,24.75,115,172.17,0,1,24,10,156
56,Tim David,RCB,187,12,9,6,50*,62.33,101,185.14,0,1,16,14,148
58,Shahrukh Khan,GT,179,15,11,5,57,29.83,100,179.00,0,1,11,13,122
59,Andre Russell,KKR,167,13,10,1,57*,18.56,102,163.72,0,1,16,14,148
60,Abdul Samad,LSG,164,13,12,4,45,20.50,93,176.34,0,0,8,14,116
61,Marcus Stoinis,PBKS,160,13,11,5,44*,26.67,86,186.04,0,0,8,15,122
65,Vipraj Nigam,DC,142,14,8,1,39,20.29,79,179.74,0,0,15,8,108
67,Washington Sundar,GT,133,6,5,0,49,26.60,80,166.25,0,0,10,7,82
68,Ruturaj Gaikwad,CSK,122,5,5,0,63,24.40,81,150.61,0,2,14,4,80
69,Sameer Rizvi,DC,121,5,4,1,58*,40.33,79,153.16,0,1,11,7,86
74,Shubham Dubey,RR,106,9,8,4,34*,26.50,66,160.60,0,0,6,8,72
75,Rahul Tewatia,GT,99,15,12,4,24*,12.38,59,167.79,0,0,6,7,66
76,Pat Cummins,SRH,97,14,9,5,22*,24.25,58,167.24,0,0,6,7,66
80,Jonny Bairstow,MI,85,2,2,0,47,42.50,46,184.78,0,0,7,5,58
84,Romario Shepherd,RCB,70,8,3,1,53*,35.00,24,291.66,0,1,5,7,62
85,Urvil Patel,CSK,68,3,3,0,37,22.67,32,212.50,0,0,5,6,56
86,Jacob Bethell,RCB,67,2,2,0,55,33.50,39,171.79,0,1,9,3,54
103,Avesh Khan,LSG,21,13,4,3,19*,21.00,12,175.00,0,0,3,1,18
105,Kusal Mendis,GT,20,1,1,0,20,20.00,10,200.00,0,0,1,2,16
108,Gerald Coetzee,GT,17,4,2,0,12,8.50,11,154.54,0,0,2,1,14
109,Jamie Overton,CSK,15,3,2,2,11*,NaN,7,214.28,0,0,1,1,10
124,Kwena Maphaka,RR,8,2,1,1,8*,NaN,2,400.00,0,0,2,0,8
125,Raj Angad Bawa,MI,8,3,1,1,8*,NaN,4,200.00,0,0,0,0,0
129,Akash Deep,LSG,6,6,2,1,6*,6.00,2,300.00,0,0,0,1,6
137,Lockie Ferguson,PBKS,4,4,1,1,4*,NaN,1,400.00,0,0,1,0,4

In [45]:
df[df["Team"]=="RCB"]

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s,Boundary Runs
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19,378
16,Phil Salt,RCB,403,13,13,1,65,33.58,229,175.98,0,4,48,22,324
28,Rajat Patidar,RCB,312,15,14,1,64,24.00,217,143.77,0,2,25,14,184
38,Jitesh Sharma,RCB,261,15,11,4,85*,37.29,148,176.35,0,1,24,17,198
41,Devdutt Padikkal,RCB,247,10,10,1,61,27.44,164,150.60,0,2,21,14,168
56,Tim David,RCB,187,12,9,6,50*,62.33,101,185.14,0,1,16,14,148
72,Liam Livingstone,RCB,112,10,8,1,54,16.00,84,133.33,0,1,4,9,70
73,Krunal Pandya,RCB,109,15,7,1,73*,18.17,86,126.74,0,1,9,4,60
77,Mayank Agarwal,RCB,95,4,4,1,41*,31.67,64,148.43,0,0,10,2,52
84,Romario Shepherd,RCB,70,8,3,1,53*,35.00,24,291.66,0,1,5,7,62
86,Jacob Bethell,RCB,67,2,2,0,55,33.50,39,171.79,0,1,9,3,54
112,Bhuvneshwar Kumar,RCB,14,14,6,3,8,4.67,25,56.00,0,0,1,0,4
138,Yash Dayal,RCB,4,15,3,1,3,2.00,8,50.00,0,0,0,0,0
155,Manoj Bhandage,RCB,1,1,1,0,1,1.00,4,25.00,0,0,0,0,0

In [46]:
df[(df["Runs"]>500)&(df["SR"]>150)]

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s,Boundary Runs
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21,478
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38,504
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24,392
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37,446
5,Shreyas Iyer,PBKS,604,17,17,5,97*,50.33,345,175.07,0,6,43,39,406
6,Yashasvi Jaiswal,RR,559,14,14,1,75,43.00,350,159.71,0,6,60,28,408
7,Prabhsimran Singh,PBKS,549,17,17,0,91,32.29,342,160.52,0,4,56,30,404
9,Jos Buttler,GT,538,14,13,4,97*,59.78,330,163.03,0,5,52,24,352
10,Nicholas Pooran,LSG,524,14,14,2,87*,43.67,267,196.25,0,5,45,40,420

In [47]:
df.to_csv("IPL@)@%_Cleaned.csv", index=False)

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s,Boundary Runs
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21,478
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38,504
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19,378
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24,392
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37,446
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,Khaleel Ahmed,CSK,1,14,2,2,1*,NaN,2,50.00,0,0,0,0,0
152,Mohit Sharma,DC,1,8,2,1,1*,1.00,3,33.33,0,0,0,0,0
153,Donovan Ferreira,DC,1,1,1,0,1,1.00,3,33.33,0,0,0,0,0
154,Digvesh Singh,LSG,1,13,2,1,1,1.00,3,33.33,0,0,0,0,0
155,Manoj Bhandage,RCB,1,1,1,0,1,1.00,4,25.00,0,0,0,0,0